DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS link;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE link (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  original_url TEXT UNIQUE NOT NULL,
  short_url TEXT UNIQUE NOT NULL,
  user_id INTEGER NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



